### ISSUE TITLE
Video recording tap-in

### ISSUE THREAD

**Issue by digitalchaotics** [fabmax/kool#2]
Hi Max,

I would love to use this engine, but I am not seeing the plug-in points I need.

I want to be able to retrieve each frame, and record it to a video file (mp4).  Where can I find the finished image after each frame?  Are there best practices around this that I should be aware of?

Thanks in advance,

**Comment by fabmax** [comment]
The final rendered images usually stay in the GPU memory since copying them back into CPU accessible memory comes with some overhead and usually is not needed. Therefore retrieving the images means a bit of extra work:

Essentially you have to render your scene into a texture and then copy back the texture content into host memory. If you use the deferred rendering pipeline the texture rendering part is already done. The image is available in the output texture of the pbr pass: `DeferredPipeline.pbrPass.colorTexture`.

The tricky part is to get the texture content back into host memory. The engine currently does not provide any functions for that because it would be a OpenGL/Vulkan feature only and the WebGL variant would not able to do that (WebGL does not provide functions for copying back textures).

However, it shouldn't be too hard to integrate something like that into your code. I guess it could look something like that (assuming you use OpenGL on JVM, completely untested and probably not working out of the box):

```java
val deferredPipeline = // setup deferred render pipeline
val outputBuffer = // allocate ByteBuffer for image output

scene.mainRenderPass.onAfterDraw += {
    // assuming this is rendered with OpenGL
    val glTex = (deferredPipeline.pbrPass.colorTexture?.loadedTexture as LoadedTextureGl?)?.texture
    if (glTex != null) {
        glGetTexImage(glTex, 0, GL_RGBA, GL_UNSIGNED_BYTE, outputBuffer)
        // outputBuffer should contain the uncompressed output image now
    }
}
```

**Comment by digitalchaotics** [comment]
Thank you!  It is exactly the pointer I needed.  I have some old code that pulls a texture out of the GPU, so now all I have to do is adapt it for this.  I'll let you know how it goes.
