### ISSUE TITLE
[Suggestion] Better physics character + heightmap world loading

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#7]
Hello fabmax, If I may suggest a better system for physics character with an (onGround detection to prevent multiple jump and flying), and without bounces glitch with rigidbody.
I think it will be way more easy for you to do it than me.

Also, I saw the noise functions (perlin noise, simplex noise and others) it is really cool ! 
Do you think it is possible to make an heightmap image loader as a new world demo ?

Thank your for your work
Protoxy

**Comment by fabmax** [comment]
Yes a better character controller is definitely still on my todo list (and it is not easy to do). I'm currently working on some tech stuff under the hood but I will probably start with a new demo soon (probably something with character physics).

Loading a heightmap image is currently difficult to do with javascript but relatively easy on JVM. The problem is to get the image data as a CPU accessible buffer. On JVM this is easy because images are loaded as a BufferedImage but on javascript it's a different story. As far as I know the only solution is to render the image into a canvas and then retrieve the canvas image data as a buffer.

Once you got the image data as a buffer it's a simple matter of reading the pixel values and adjusting the height axis in your mesh.
